# Generated by Django 2.2.5 on 2019-10-03 02:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('_title', models.CharField(max_length=100)),
                ('_key_words', models.TextField(blank=True)),
                ('_bin', models.BinaryField()),
                ('_approved', models.BooleanField(default=False)),
                ('_upload_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundBankUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_user_id', models.CharField(max_length=100, unique=True)),
                ('_username', models.CharField(max_length=100)),
                ('_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('_last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_listened_count', models.PositiveIntegerField(default=0)),
                ('_sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_rank', to='sound_bank.Sound')),
                ('_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_sound_rank', to='sound_bank.SoundBankUser')),
            ],
        ),
        migrations.AddField(
            model_name='sound',
            name='_uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sounds', to='sound_bank.SoundBankUser'),
        ),
        migrations.AddConstraint(
            model_name='soundrank',
            constraint=models.UniqueConstraint(fields=('_user', '_sound'), name='sound rank constraint'),
        ),
    ]
