# Generated by Django 2.2.5 on 2019-09-27 20:41
import json
import pytz
from base64 import b64decode
from datetime import datetime
from django.db import migrations

with open('sound_bank/default_sounds/default_sounds.json', 'r') as file:
    # [{'name':, 'key_words':, 'file_bin':},]
    sounds = json.loads(file.read())


def import_default_sounds(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Sound = apps.get_model('sound_bank', 'Sound')
    for sound in sounds:
        Sound.objects.create(_title=sound['name'], _key_words=sound['key_words'], _bin=b64decode(sound['file_bin']),
                             _upload_datetime=pytz.utc.localize(datetime.utcnow()), _approved=True)


def remove_all_sounds(apps, schema_editor):
    Sound = apps.get_model('sound_bank', 'Sound')
    Sound.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('sound_bank', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=import_default_sounds, reverse_code=remove_all_sounds),
    ]
