# Generated by Django 2.2.5 on 2019-09-27 20:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_telegram_id', models.CharField(max_length=100)),
                ('_username', models.CharField(max_length=100)),
                ('_first_name', models.CharField(max_length=100)),
                ('_last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('_title', models.CharField(max_length=100)),
                ('_key_words', models.TextField(blank=True)),
                ('_bin', models.BinaryField()),
                ('_upload_date', models.DateField(blank=True, null=True)),
                ('_uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sounds', to='app.BotUser')),
            ],
        ),
        migrations.CreateModel(
            name='SoundRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_sent_count', models.PositiveIntegerField(default=0)),
                ('_bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_sounds', to='app.BotUser')),
                ('_sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sound')),
            ],
        ),
        migrations.AddConstraint(
            model_name='soundrank',
            constraint=models.UniqueConstraint(fields=('_bot_user', '_sound'), name='sound rank constraint'),
        ),
    ]
