# Generated by Django 2.2.5 on 2019-09-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='_upload_date',
        ),
        migrations.AddField(
            model_name='sound',
            name='_upload_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
