# Generated by Django 2.2.5 on 2019-09-27 20:41
import json
import pytz
from base64 import b64decode
from datetime import datetime
from django.db import migrations

with open('app/default_sounds/default_sounds.json', 'r') as file:
    # [{'name':, 'key_words':, 'file_bin':},]
    sounds = json.loads(file.read())


def import_default_sounds(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Sound = apps.get_model('app', 'Sound')
    for sound in sounds:
        Sound.objects.create(_title=sound['name'], _key_words=sound['key_words'], _bin=b64decode(sound['file_bin']),
                             _upload_datetime=pytz.utc.localize(datetime.utcnow()))


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190927_2050'),
    ]

    operations = [
        migrations.RunPython(import_default_sounds),
    ]
