# Generated by Django 2.2.5 on 2019-10-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('_title', models.CharField(max_length=100)),
                ('_tags', models.TextField(blank=True)),
                ('_bin', models.BinaryField()),
                ('_upload_datetime', models.DateTimeField()),
                ('_is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('_username', models.CharField(max_length=100)),
                ('_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('_last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_count', models.PositiveIntegerField(default=0)),
                ('_sound', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='_rank', to='web_sound_bank.Sound')),
                ('_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_sound_bank.User')),
            ],
        ),
        migrations.AddField(
            model_name='sound',
            name='_uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_sounds', to='web_sound_bank.User'),
        ),
        migrations.AddConstraint(
            model_name='soundrank',
            constraint=models.UniqueConstraint(fields=('_user', '_sound'), name='sound rank constraint'),
        ),
    ]
