# Generated by Django 2.2.5 on 2019-09-27 20:41
import hashlib
import json
import pytz
from base64 import b64decode
from datetime import datetime
from django.db import migrations

with open('web_sound_bank/default_sounds/default_sounds.json', 'r') as file:
    # [{'name':, 'key_words':, 'file_bin':},]
    sounds = json.loads(file.read())


default_user_data = {'id': 'DEFAULT_ID', 'username': 'DEFAULT_USERNAME'}


def import_default_sounds(Sound, user):
    for sound in sounds:
        sound_title = sound['name']
        sound_tags = sound['key_words']
        binary_data = b64decode(sound['file_bin'])
        sound_id = hashlib.sha3_256(binary_data + user._id.encode('utf-8')).hexdigest()

        Sound.objects.create(_id=sound_id, _title=sound_title, _tags=sound_tags, _bin=binary_data,
                             _upload_datetime=pytz.utc.localize(datetime.utcnow()), _is_approved=True,
                             _uploader=user)


def create_default_user(User):
    return User.objects.create(_id=default_user_data['id'], _username=default_user_data['username'])


def migration(apps, schema_editor):
    User = apps.get_model('web_sound_bank', 'User')
    Sound = apps.get_model('web_sound_bank', 'Sound')

    user = create_default_user(User)
    import_default_sounds(Sound, user)


def revert_migration(apps, schema_editor):
    User = apps.get_model('web_sound_bank', 'User')
    Sound = apps.get_model('web_sound_bank', 'Sound')

    Sound.objects.all().delete()
    User.objects.get(_id=default_user_data['id']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('web_sound_bank', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=migration, reverse_code=revert_migration),
    ]
