# Generated by Django 2.2.5 on 2019-11-03 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_sound_bank', '0002_import_default_sounds_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_token', models.CharField(max_length=64, unique=True)),
                ('_expiration_timestamp', models.BigIntegerField()),
                ('_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='web_sound_bank.User')),
            ],
        ),
    ]
